### ISSUE TITLE
The bt Template for 010 Editor does not work

### ISSUE THREAD

**Issue by MewtwoFanz** [Lightboom9/p5rpc.SkillTableExpanded#1]
I can't get it to open at all, and It has so many errors at different points in the template that I can't fix it easily.

**Comment by Lightboom9** [comment]
You don't have to fix it at all, it works fine. You likely haven't placed it in the correct location - it should be placed in the same folder as the rest of your templates, like the normal p5r_tbl template.

**Comment by Lightboom9** [comment]
I believe the problem was resolved outside of the Issue.
